### PR TITLE
Add invoke receipt properties to deploy receipt

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`api/starknet_api_openrpc.json` line 620 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAiz5tpDj-IrThiLrPM:-NAiz5tpDj-IrThiLrPN:b98syud) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a2fd198a59234093413a8f3d15d6914c0aed12a1/api/starknet_api_openrpc.json#L620)):*
> ```JSON
>                 },
>                 {
>                     "$ref": "#/components/errors/BLOCK_NOT_FOUND"
> ```

I forgot to change this when I rebased PR 51 (not sure how it passed the tests)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1492 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmbiPY5hGvDzF2xVGL:-NAmbiPY5hGvDzF2xVGM:budd76g) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a2fd198a59234093413a8f3d15d6914c0aed12a1/api/starknet_api_openrpc.json#L1492)):*
> ```JSON
>                     },
>                     {
>                         "$ref": "#/components/schemas/INVOKE_TXN_RECEIPT_PROPERTIES"
> ```

The name becomes weird now (as it's shared with deploy)
Maybe we can call it EXECUTION_RECEIPT_PROPERTIES or something simillar

This also needs to be a part of declare txs, as v1 declare txs go through validate_declare which can emit events / send messages

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1492 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmbiPY5hGvDzF2xVGL:-NAmiCCG7DfbsRGB26NA:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a2fd198a59234093413a8f3d15d6914c0aed12a1/api/starknet_api_openrpc.json#L1492)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The name becomes weird now (as it's shared with deploy)
Maybe we can call it EXECUTION_RECEIPT_PROPERTIES or something simillar

This also needs to be a part of declare txs, as v1 declare txs go through validate_declare which can emit events / send messages 
</blockquote></details>

Done.

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 1492 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmbiPY5hGvDzF2xVGL:-NAmiUkU2u9eLKB6tIFp:bfi4xj5) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a2fd198a59234093413a8f3d15d6914c0aed12a1/api/starknet_api_openrpc.json#L1492)):*
> This also needs to be a part of declare txs, as v1 declare txs go through validate_declare which can emit events / send messages

this is then shared by all transaction types?

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @ArielElp, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1438 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmipiyEoLGYYXsNBga:-NAmipiyEoLGYYXsNBgb:bcjd9s2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/500386c0b2bfc3056503f1523fcf8b2ec58fbae6/api/starknet_api_openrpc.json#L1438)):*
> ```JSON
>                 ]
>             },
>             "EXECUTION_RECEIPT_PROPERTIES": {
> ```

@arielelp , @anatgstarkware ,

What am I missing here?
if this is shared by all transaction types, why isn't this part of the COMMON_RECEIPT_PROPERTIES?
can't an L1 handler also emit events and messages?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1438 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmipiyEoLGYYXsNBga:-NAmnH22ACx2y2o56bSl:biw8y1v) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/500386c0b2bfc3056503f1523fcf8b2ec58fbae6/api/starknet_api_openrpc.json#L1438)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

@arielelp , @anatgstarkware ,

What am I missing here?
if this is shared by all transaction types, why isn't this part of the COMMON_RECEIPT_PROPERTIES?
can't an L1 handler also emit events and messages?
</blockquote></details>

Right. Done.

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1492 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NAmbiPY5hGvDzF2xVGL:-NAmpnswBnsg7NjxV41o:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a2fd198a59234093413a8f3d15d6914c0aed12a1/api/starknet_api_openrpc.json#L1492)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

> This also needs to be a part of declare txs, as v1 declare txs go through validate_declare which can emit events / send messages

this is then shared by all transaction types?
</blockquote></details>

Done.

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware)

___
*[`api/starknet_api_openrpc.json` line 1501 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NBD3t3c2Ifj7UAx8sYH:-NBD3t3c2Ifj7UAx8sYI:brcc3zl) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4006e1720fb638f1139c1e071bb65b0e37d0e5cd/api/starknet_api_openrpc.json#L1501)):*
> ```JSON
>                 ]
>             },
>             "PENDING_TXN_RECEIPT": {
> ```

Why don't we have types for pending receipts? currently, the only difference is that deploy has the contract address, but this isn't reflected here (this situation existed prior to this PR I guess)

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1501 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-NBD3t3c2Ifj7UAx8sYH:-NBDF7lvA54ZL9glcw7i:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4006e1720fb638f1139c1e071bb65b0e37d0e5cd/api/starknet_api_openrpc.json#L1501)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Why don't we have types for pending receipts? currently, the only difference is that deploy has the contract address, but this isn't reflected here (this situation existed prior to this PR I guess)
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/52#-:-NBDLKkr0efrvN7Nl1R5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
