### PR TITLE
Refactor block structure and add pending block support

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1053 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N5-vbch4XdrtqlB0bVR:-N5-vbch4XdrtqlB0bVS:b-jokt4l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L1053)):*
> ```JSON
>                 }
>             },
>             "PENDING_BLOCK": {
> ```

so you created this just to make a distinction in the header?
why not have `COMMON_BLOCK_PROPERTIES` and then have it reused here and in the `BLOCK_HEADER` object?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1053 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N5-vbch4XdrtqlB0bVR:-N502ARDC-0JtKyebaMg:b-2nhiz6) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L1053)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so you created this just to make a distinction in the header?
why not have `COMMON_BLOCK_PROPERTIES` and then have it reused here and in the `BLOCK_HEADER` object?

</blockquote></details>

I think header/body separation is helpful in general

I can do the latter, but the advantage now is that the pending block is separate from "standard" blocks.  Additionally, "COMMON_BLOCK_PROPERTIES" kind of enshrines pending, common to what?

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N50OOuk2a57puhkfQVL:-N50OOuk2a57puhkfQVM:b1yo6sv) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L4)):*
> ```JSON
>     "openrpc": "1.0.0-rc1",
>     "info": {
>         "version": "0.12.0",
> ```

the current version in master is 0.12.0, this should be 0.13.0
___
*[`api/starknet_api_openrpc.json` line 1053 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N5-vbch4XdrtqlB0bVR:-N50Oax7CoqLv511Il4v:b-jhes1t) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L1053)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think header/body separation is helpful in general

I can do the latter, but the advantage now is that the pending block is separate from "standard" blocks.  Additionally, "COMMON_BLOCK_PROPERTIES" kind of enshrines pending, common to what? 
</blockquote></details>

i see your point about "enshrining" the pending block.
The tradeoff here is that these properties (timestamp, seq address, parent hash) are duplicated.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N50OOuk2a57puhkfQVL:-N54SurPD0wXF_H7W1OZ:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L4)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the current version in master is 0.12.0, this should be 0.13.0
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1053 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-N5-vbch4XdrtqlB0bVR:-N54SvwF-5KEs08sG1hf:b-pqbbvg) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a9a4c10e22bee9dee4bbc8e78e780789e79acc6f/api/starknet_api_openrpc.json#L1053)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

i see your point about "enshrining" the pending block.
The tradeoff here is that these properties (timestamp, seq address, parent hash) are duplicated.
</blockquote></details>

I can live with that, if for some reason this gets too big in the future we can add common properties

**Review by lior-stark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6#-:-N555yxy7ZQ7DWcZnFbE:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lior-stark)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
