### PR TITLE
Change to block id

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @ArielElp, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 475 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gu92X6opeNdU_H-eG:-N6gu92X6opeNdU_H-eH:bdhs94) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L475)):*
> ```JSON
>         {
>             "name": "starknet_getLatestBlockID",
>             "summary": "Get the most recent accepted block id",
> ```

since block_id might be many things, what is returned here?
if I always return "latest" does it satisfies this API?

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @ArielElp, and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 16 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gyZXm4Liayp0dKb_l:-N6gyZXm4Liayp0dKb_m:bet3u3w) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L16)):*
> ```JSON
>                 {
>                     "name": "block_id",
>                     "description": "The hash of the requested block, number (height) of the requested block, or a block tag",
> ```

it's hash *or* number or tag, right?
this description is not precise in that respect.
also below for other cases.
___
*[`api/starknet_api_openrpc.json` line 750 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gzYzEB58Y1HRyNx9Y:-N6gzYzFBl0NeZxWEyUu:b-nf3pc0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L750)):*
> ```JSON
>             "BLOCK_ID": {
>                 "title": "Block hash, number or tag",
>                 "oneOf": [
> ```

this would mean that the way to distinguish between a hash and a number is looking at the prefix.

This prevents another change I wanted to make where all numbers are returned as hex.
In the write API document it's already like that (`NUM_AS_HEX`).

what if we add a simple property here that is one of HASH|NUM|TAG, and let the client know.

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @ArielElp, @bbrandtom, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 16 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gyZXm4Liayp0dKb_l:-N6h3NQu7ftdcEpruZVF:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L16)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

it's hash *or* number or tag, right?
this description is not precise in that respect.
also below for other cases.
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 475 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gu92X6opeNdU_H-eG:-N6h3QAA1-FfxQGzxLZx:bbu3dev) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L475)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

since block_id might be many things, what is returned here?
if I always return "latest" does it satisfies this API?
</blockquote></details>

My bad. I wanted an alternative to starknet_blockNumber that returns both the number and the hash.
It can also be called starknet_blockID or starknet_blockId. WDYT?

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @ArielElp, @bbrandtom, and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 481 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6qlLhO3id5__dMwcAT:-N6qlLhP5HIpdlmWyQRI:boj7cth) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/59c577d5f2e04b5eb8a59f8038147d5f0364d4fa/api/starknet_api_openrpc.json#L481)):*
> ```JSON
>                 "description": "The latest block hash and number",
>                 "schema": {
>                     "allOf": [
> ```

I'm not sure how this will work.
This means the result has to be a number and hash at the same time.

do you want to return either a number and a hash? 
or an object that returns both?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 750 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6gzYzEB58Y1HRyNx9Y:-N6h4pAN2lmHuGcaEirJ:bt2vr1b) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/c188383c821e0c8a82828078cb8e8d266cc2f15f/api/starknet_api_openrpc.json#L750)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this would mean that the way to distinguish between a hash and a number is looking at the prefix.

This prevents another change I wanted to make where all numbers are returned as hex.
In the write API document it's already like that (`NUM_AS_HEX`).

what if we add a simple property here that is one of HASH|NUM|TAG, and let the client know.
</blockquote></details>

Fixed.
___
*[`api/starknet_api_openrpc.json` line 481 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/17#-N6qlLhO3id5__dMwcAT:-N6rQd0JB89PpmeqjiTz:bt2vr1b) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/59c577d5f2e04b5eb8a59f8038147d5f0364d4fa/api/starknet_api_openrpc.json#L481)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I'm not sure how this will work.
This means the result has to be a number and hash at the same time.

do you want to return either a number and a hash? 
or an object that returns both?

</blockquote></details>

Fixed.

**Review by lior-stark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @dan-starkware)

**Pull request merged**
