### PR TITLE
write api: declare transaction

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_write_api.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pa7A386644YWNWb6G:-N2pa7A464RLOI96DsCX:b3jytyi) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L4)):*
> ```JSON
>     "openrpc": "1.0.0-rc1",
>     "info": {
>         "version": "0.2.0",
> ```

this should be 0.3.0
___
*[`api/starknet_write_api.json` line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2paDOZ34Qh9EzL0fuD:-N2paDOZ34Qh9EzL0fuE:bfdqvrq) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L66)):*
> ```JSON
>                 {
>                     "name": "contract_class",
>                     "description": "The salt used for calculting the contract address",
> ```

I don't think that's the right description
___
*[`api/starknet_write_api.json` line 79 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2paMYT8XB-3scezLKa:-N2paMYT8XB-3scezLKb:b-tdb52z) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L79)):*
> ```JSON
>                     "properties": {
>                         "transaction_hash": {
>                             "title": "The hash of the deploy transaction",
> ```

the hash of the *declare* transaction, right?
___
*[`api/starknet_write_api.json` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pao-oAWUA6Pm1HLrM:-N2pao-oAWUA6Pm1HLrN:b-hkj1lt) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L151)):*
> ```JSON
>         "contentDescriptors": {},
>         "schemas": {
>             "CONTRACT_CLASS": {
> ```

I'm thinking this should be moved to the `starknet_api_openrpc.json` file since it should be used there for retrieving the class.
The question is whether this will be the same type returned.

wdyt?
___
*[`api/starknet_write_api.json` line 229 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pagaLBQ09irqB4rVW:-N2pagaLBQ09irqB4rVX:b-dijx15) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L229)):*
> ```JSON
>         "errors": {
>             "INVALID_CONTRACT_CLASS": {
>                 "code": 50,
> ```

why 50?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_write_api.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pa7A386644YWNWb6G:-N2qSzaM4JgbZxTJpI8x:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L4)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this should be 0.3.0
</blockquote></details>

Done.
___
*[`api/starknet_write_api.json` line 66 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2paDOZ34Qh9EzL0fuD:-N2qT-WZ2hVqe4xUfuFI:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L66)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I don't think that's the right description
</blockquote></details>

Done.
___
*[`api/starknet_write_api.json` line 79 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2paMYT8XB-3scezLKa:-N2qT4ssCQ4yqB7wdViG:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L79)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the hash of the *declare* transaction, right?
</blockquote></details>

Done.
___
*[`api/starknet_write_api.json` line 151 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pao-oAWUA6Pm1HLrM:-N2tbXsh-D-Xj-omFq4W:bejeyqs) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L151)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I'm thinking this should be moved to the `starknet_api_openrpc.json` file since it should be used there for retrieving the class.
The question is whether this will be the same type returned.

wdyt?
</blockquote></details>

makes sense, done
___
*[`api/starknet_write_api.json` line 229 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2pagaLBQ09irqB4rVW:-N2qTCDP2IkQowPFvIAS:b-47xkk7) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/808398dd3c8b8d0155f80c05963080d9b12b13aa/api/starknet_write_api.json#L229)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why 50?
</blockquote></details>

didn't change this, I'm assuming it's just > existing error codes

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1107 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2tjcczCQ4RJjofcS8d:-N2tjcczCQ4RJjofcS8e:byfua6k) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e62ecb1b934daa33e49f1cc3ac98b7fd6223e77a/api/starknet_api_openrpc.json#L1107)):*
> ```JSON
>                 "type": "object",
>                 "properties": {
>                     "offset": {
> ```

why do we need the offset on top of the selector?
and the client of the API needs it?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1107 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2tjcczCQ4RJjofcS8d:-N2u-hu997GmUf0FPcs6:b-5izdol) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e62ecb1b934daa33e49f1cc3ac98b7fd6223e77a/api/starknet_api_openrpc.json#L1107)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why do we need the offset on top of the selector?
and the client of the API needs it?
</blockquote></details>

This object is intended for execution, I'm guessing it's used in the vm preparation (initial PC and stuff)

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_write_api.json` line 124 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2u3d2B1CGedu1pIz7_:-N2u6JZP1fG1o9XiAs6q:b-t1qiy8) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e62ecb1b934daa33e49f1cc3ac98b7fd6223e77a/api/starknet_write_api.json#L124)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

you don't want to change the name of the parameter as well?
</blockquote></details>

No, we don't change the old deploy tx as far as I recall (on our API), so we can keep the spec aligned until the deprecation
___
*[`api/starknet_write_api.json` line 127 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2u3E9h7EofDQFmOWrN:-N2u78_C67359U98qmF0:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e62ecb1b934daa33e49f1cc3ac98b7fd6223e77a/api/starknet_write_api.json#L127)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

where is this definition?
I couldn't find it under the `schemas` here.

there should probably be a definition there that points to the `starknet_api_openrpc` file, like in the `FELT` case below.
</blockquote></details>

Done.

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

___
*[`api/starknet_write_api.json` line 127 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-N2u3E9h7EofDQFmOWrN:-N2uShof6JIMAqRj6aBB:b-ibbg6y) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e62ecb1b934daa33e49f1cc3ac98b7fd6223e77a/api/starknet_write_api.json#L127)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Done.
</blockquote></details>

last time i checked this didn't work, but theoretically it should.
but I think we can proceed this way.

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/2#-:-N2uSyer1ricuheigbBE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
