### PR TITLE
StarkNet 0.11.0 adjustments

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)

### CODE REVIEW

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1162 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSvffd7vdoizeU0CGV:-NKSvffd7vdoizeU0CGW:b-atmi9z) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/f162039c3d9a89062aa73c1079a6e6b86f47c1c4/api/starknet_api_openrpc.json#L1162)):*
> ```JSON
>                     },
>                     {
>                         "$ref": "#/components/schemas/BROADCASTED_DEPLOY_TXN"
> ```

Can we erase `BROADCASTED_DEPLOY_TXN`?
___
*[`api/starknet_api_openrpc.json` line 1284 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSwPxCEP2aGiUTfkvD:-NKSwPxCEP2aGiUTfkvE:b-24a3q7) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1284)):*
> ```JSON
>                 ]
>             },
>             "BROADCASTED_DECLARE_V1_TXN": {
> ```

Can we change the name to `BROADCASTED_DECLARE_TXN_V1`? Same for V2?
___
*[`api/starknet_api_openrpc.json` line 1305 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSw63z1F0qlC6V4q-q:-NKSw64-EP32TTK97zn8:b-5z5thb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1305)):*
> ```JSON
>                 ]
>             },
>             "BROADCASTED_DECLARE_V2_TXN": {
> ```

Can this be `BROADCASTED_DECLARE_V1_TXN` + `compiled_class_hash`?
___
*[`api/starknet_api_openrpc.json` line 1826 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSu1RH1geXjYqY6aG9:-NKSu1RH1geXjYqY6aGA:b-k511p0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1826)):*
> ```JSON
>                     },
>                     "entry_points_by_type": {
>                         "$ref": "#/components/schemas/DEPRECATED_CAIRO_ENTRY_POINTS"
> ```

Do we use `DEPRECATED_CAIRO_ENTRY_POINTS` anywhere else? If not, can we flatten it here? Same for `SIERRA_ENTRY_POINTS` and `CAIRO_ENTRY_POINTS`?
___
*[`api/starknet_api_openrpc.json` line 1837 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSzMcD59oZjFw4BBtU:-NKSzMcD59oZjFw4BBtV:b-gqeyad) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1837)):*
> ```JSON
>                 ]
>             },
>             "CONTRACT_ENTRY_POINTS": {
> ```

Where do we need `CONTRACT_ENTRY_POINTS`?
___
*[`api/starknet_api_openrpc.json` line 1841 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSzV-U3eFeWnB7GH-8:-NKSzV-U3eFeWnB7GH-9:b-nobkob) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1841)):*
> ```JSON
>                 "properties": {
>                     "CONSTRUCTOR": {
>                         "$ref": "#/components/schemas/CAIRO_ENTRY_POINT_LIST"
> ```

Can we avoid the list types as well?



_Code quote:_
```JSON
CAIRO_ENTRY_POINT_LIST
```

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware)

___
*[`api/starknet_api_openrpc.json` line 1162 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSvffd7vdoizeU0CGV:-NKqNaWq25HxVZlB7H8t:bu0rs8d) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/f162039c3d9a89062aa73c1079a6e6b86f47c1c4/api/starknet_api_openrpc.json#L1162)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Can we erase `BROADCASTED_DEPLOY_TXN`?
</blockquote></details>

Yep, removed
___
*[`api/starknet_api_openrpc.json` line 1305 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSw63z1F0qlC6V4q-q:-NKqOelT9-pmh9GFmRc-:b4xy0n) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1305)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Can this be `BROADCASTED_DECLARE_V1_TXN` + `compiled_class_hash`?
</blockquote></details>

Classes are a different object (deprecated vs new)
___
*[`api/starknet_api_openrpc.json` line 1826 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSu1RH1geXjYqY6aG9:-NKqTCi64LRQBzMRKMgv:bbqm8u) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1826)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Do we use `DEPRECATED_CAIRO_ENTRY_POINTS` anywhere else? If not, can we flatten it here? Same for `SIERRA_ENTRY_POINTS` and `CAIRO_ENTRY_POINTS`?
</blockquote></details>

Flattened
___
*[`api/starknet_api_openrpc.json` line 1837 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSzMcD59oZjFw4BBtU:-NKqTqvd8yxDC9UMxRMo:b-mm54qh) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1837)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Where do we need `CONTRACT_ENTRY_POINTS`?
</blockquote></details>

Currently, it's not used. This boils down to whether or not we want get_compiled_class in the RPC. Thinking more about it, I think that the answer is no.

1. Full nodes will need it internally to execute (until there's some other way to execute Sierra, which is futuristic for now)
2. This is more of an implementation detail; I'm not sure a consumer has an interest in the Cairo code, which only serves the purpose of being able to prove executions of that class.
3. You can compile the Sierra locally to get it (hopefully, if you use the same compiler version, you get the same result)

Removed for now (this + list + entry point type), WDYT?
___
*[`api/starknet_api_openrpc.json` line 1841 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKSzV-U3eFeWnB7GH-8:-NKqWd2aEAWLixCVat1n:b-34vmyd) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/bebb788884a946929a63b176ad5f6702091fd89b/api/starknet_api_openrpc.json#L1841)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Can we avoid the list types as well?
</blockquote></details>

See above

**Comment by anatgstarkware** [comment]
*[`api/starknet_api_openrpc.json` line 1158 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKqeVgv2ll2w4NvhIPV:-NKqeVgv2ll2w4NvhIPW:bou5pm) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/d2b6135cc4a49ab5af3680e510f7f22c7036ae37/api/starknet_api_openrpc.json#L1158)):*
> ```JSON
>                     },
>                     {
>                         "$ref": "#/components/schemas/DEPLOY_TXN"
> ```

Do we still need the DEPLOY_TXN? and the DEPLOY_TXN_RECEIPT?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware)

___
*[`api/starknet_api_openrpc.json` line 1158 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NKqeVgv2ll2w4NvhIPV:-NLG4xVwA2g0gWqgNkPP:bultjvp) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/d2b6135cc4a49ab5af3680e510f7f22c7036ae37/api/starknet_api_openrpc.json#L1158)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Do we still need the DEPLOY_TXN? and the DEPLOY_TXN_RECEIPT?
</blockquote></details>

We're still gonna have them in historical blocks, these gotta stay until regenesis.

**Comment by anatgstarkware** [comment]
*[`api/starknet_api_openrpc.json` line 1794 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NMcK-MSDfJXHtWHT0fA:-NMcK-MSDfJXHtWHT0fB:bxcvizi) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1794)):*
> ```JSON
>                 }
>             },
>             "COMPILED_CONTRACT_CLASS": {
> ```

so we don't use this anywhere?

**Review by eitan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1794 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NO5AZpd9E_NTfH5ivmf:-NO5AZpd9E_NTfH5ivmg:b-dbffym) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1794)):*
> ```JSON
>                 }
>             },
>             "COMPILED_CONTRACT_CLASS": {
> ```

Not sure who this file is used by, but in the code, it is referenced as "compiled class" (without the contract)



_Code quote:_
```JSON
COMPILED_CONTRACT_CLASS
```
___
*[`api/starknet_api_openrpc.json` line 1910 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NO5B8AWCBlmqIP37U7B:-NO5B8AWCBlmqIP37U7C:be5h8my) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1910)):*
> ```JSON
>                     "poseidon",
>                     "ecdsa",
>                     "ec_op",
> ```

Theis enum is different order in the repo, maybe we should keep it in the same order.
The builtins order from left to write (according to `os.cairo` in starknet): `pedersen range_check ecdsa bitwise ec_op poseidon`

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @eitan-starkware)

___
*[`api/starknet_api_openrpc.json` line 1794 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NMcK-MSDfJXHtWHT0fA:-NO_Twfi2PiOxg6o51N_:b-hfpv0l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1794)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

so we don't use this anywhere?
</blockquote></details>

removed
___
*[`api/starknet_api_openrpc.json` line 1794 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NO5AZpd9E_NTfH5ivmf:-NO_TxgDDKbDrjeYXgkr:bm8qjxh) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1794)):*
<details><summary><i>Previously, eitan-starkware (Eitan) wrote…</i></summary><blockquote>

Not sure who this file is used by, but in the code, it is referenced as "compiled class" (without the contract)
</blockquote></details>

removed from the RPC
___
*[`api/starknet_api_openrpc.json` line 1910 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-NO5B8AWCBlmqIP37U7B:-NO_VijDDxaXiviCvCNC:b-moj1oe) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2303224ce5c07fddfacb4796332b1a34517314bf/api/starknet_api_openrpc.json#L1910)):*
<details><summary><i>Previously, eitan-starkware (Eitan) wrote…</i></summary><blockquote>

Theis enum is different order in the repo, maybe we should keep it in the same order.
The builtins order from left to write (according to `os.cairo` in starknet): `pedersen range_check ecdsa bitwise ec_op poseidon`
</blockquote></details>

removed this, currently compiled_class is not represented in the RPC at all

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65#-:-NOcftom9N7fxtYSBc9z:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ArielElp and @eitan-starkware)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
