### PR TITLE
Pack storage diff entries per contract address

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)

### CODE REVIEW

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 1111 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-N7PVstw6vd5ZmiIbwuM:-N7PVstw6vd5ZmiIbwuN:b-gbnkpw) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/eacda031b9082b49fea4916ed96481d37403e969/api/starknet_api_openrpc.json#L1111)):*
> ```JSON
>                         "$ref": "#/components/schemas/FELT"
>                     },
>                     "storage_entries": {
> ```

might be worth adding a description for `storage_entries`

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1111 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-N7PVstw6vd5ZmiIbwuM:-N7Pjz322YJW94Ijyowd:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/eacda031b9082b49fea4916ed96481d37403e969/api/starknet_api_openrpc.json#L1111)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

might be worth adding a description for `storage_entries`
</blockquote></details>

Done

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @dan-starkware)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-:-N7Ub5Ox98hWdppPedBB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @dan-starkware)

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @bbrandtom, and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 1104 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-N8Hyyj3E889Ho-B2NPr:-N8Hyyj3E889Ho-B2NPs:b-1x0bxu) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/affa4adf576bb4e3fa2a0490a320bc35ef7ab185/api/starknet_api_openrpc.json#L1104)):*
> ```JSON
>                 }
>             },
>             "STORAGE_DIFF_ITEM": {
> ```

rename to CONTRACT_STORAGE_DIFF

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1104 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-N8Hyyj3E889Ho-B2NPr:-N8wNE0IAbjt9tEOjVdn:bfol24) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/affa4adf576bb4e3fa2a0490a320bc35ef7ab185/api/starknet_api_openrpc.json#L1104)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

rename to CONTRACT_STORAGE_DIFF
</blockquote></details>

Changed to CONTRACT_STORAGE_DIFF_ITEM, is that ok?

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26#-:-N8xNdCU1rrLF_bpVAKk:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bbrandtom, @dan-starkware, and @lior-stark)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @bbrandtom and @dan-starkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @dan-starkware)

**Pull request merged**
