### PR TITLE
add l1_handler transaction

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1305 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jl6MaEM-vJ12Y4JQE:-N9jl6MaEM-vJ12Y4JQF:b-scomui) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6141d977d9b15956dbf07ca55c6f37a85af7e4ce/api/starknet_api_openrpc.json#L1305)):*
> ```JSON
>                 ]
>             },
>             "L1_HANDLER_TXN": {
> ```

this is the object declaration, but where is it used?
___
*[`api/starknet_api_openrpc.json` line 1349 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jku1q10B5RavBoQ_P:-N9jku1q10B5RavBoQ_Q:b1lg8zi) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/417492b0ff4def4c2c3eee44943ee0bcac0da8c0/api/starknet_api_openrpc.json#L1349)):*
> ```JSON
>                         }
>                     },
>                     "l1_origin_message": {
> ```

this isn't needed?
___
*[`api/starknet_api_openrpc.json` line 1412 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jkpPw3rB2ThKNWB_-:-N9jkpPw3rB2ThKNWB_0:bajc9cg) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6141d977d9b15956dbf07ca55c6f37a85af7e4ce/api/starknet_api_openrpc.json#L1412)):*
> ```JSON
>                 "$ref": "#/components/schemas/COMMON_RECEIPT_PROPERTIES"
>             },
>             "L1_HANDLER_TXN_RECEIPT": {
> ```

so this is just an alias to `COMMON_RECEIPT_PROPERTIES`?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1305 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jl6MaEM-vJ12Y4JQE:-N9k2akvDzSsnJDotPR_:biyidl0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6141d977d9b15956dbf07ca55c6f37a85af7e4ce/api/starknet_api_openrpc.json#L1305)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this is the object declaration, but where is it used?
</blockquote></details>

forgot to add it to TXN, done
___
*[`api/starknet_api_openrpc.json` line 1349 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jku1q10B5RavBoQ_P:-N9kA7qRDTzZp178yvLr:b-hfpv0l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/417492b0ff4def4c2c3eee44943ee0bcac0da8c0/api/starknet_api_openrpc.json#L1349)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this isn't needed?
</blockquote></details>

removed
___
*[`api/starknet_api_openrpc.json` line 1412 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jkpPw3rB2ThKNWB_-:-N9k2LXC2T2aDVvtytsh:b2xdn2l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6141d977d9b15956dbf07ca55c6f37a85af7e4ce/api/starknet_api_openrpc.json#L1412)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so this is just an alias to `COMMON_RECEIPT_PROPERTIES`?
</blockquote></details>

Yes, I felt it's clearer to add this named reference - to be used in the TXN_RECEIPT schema

**Review by lior-stark — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1349 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jku1q10B5RavBoQ_P:-N9p1Jro5eiVCpOt_8Wo:buy86w1) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/417492b0ff4def4c2c3eee44943ee0bcac0da8c0/api/starknet_api_openrpc.json#L1349)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

removed
</blockquote></details>

yes, i understand. I'm asking why remove it - it's not needed?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1349 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-N9jku1q10B5RavBoQ_P:-N9yygNWE3MvT3RwZV-o:bobvf7s) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/417492b0ff4def4c2c3eee44943ee0bcac0da8c0/api/starknet_api_openrpc.json#L1349)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

yes, i understand. I'm asking why remove it - it's not needed?
</blockquote></details>

Currently, it's not used
This object can be reconstructed from the transaction on L2, so there is no point in having an extra field in the receipt (this is how it was used previously).
I think that it makes sense that the rpc only knows about the L2 representation of the message, consumers can show the L1 representation depending on the usecase.

**Review by lior-stark — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45#-:-N9zHlUKDp3YafvZvdRx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
