### PR TITLE
event filters to support multiple values

### PR DESCRIPTION
**Pull request by lior-stark**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)

### CODE REVIEW

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 762 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-NCFIKAH7L24h3I_fOi8:-NCFIKAH7L24h3I_fOi9:b-1ak2qe) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/60b87d442ffb7500229808d158b6211fc2d9ae9f/api/starknet_api_openrpc.json#L762)):*
> ```JSON
>                     "keys": {
>                         "title": "filter key values",
>                         "description": "The values used to filter the events",
> ```

WDYT about adding an example here, e.g. add "the filter [[1,2],[],[3,4]] is interpreted as (key1=1 or key1 = 2) and (key3=3 or key3=4)"?

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 762 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-NCFIKAH7L24h3I_fOi8:-NCFMPPl33rhDtbfvYcq:b-xusf7l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/60b87d442ffb7500229808d158b6211fc2d9ae9f/api/starknet_api_openrpc.json#L762)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

WDYT about adding an example here, e.g. add "the filter [[1,2],[],[3,4]] is interpreted as (key1=1 or key1 = 2) and (key3=3 or key3=4)"?
</blockquote></details>

you mean in the description?
I think it's not the best place for a good documentation.
that's why I created the other script I sent you in another message.

**Comment by Mirko-von-Leipzig** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)
> 
> _[`api/starknet_api_openrpc.json` line 762 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-NCFIKAH7L24h3I_fOi8:-NCFIKAH7L24h3I_fOi9:b-1ak2qe) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/60b87d442ffb7500229808d158b6211fc2d9ae9f/api/starknet_api_openrpc.json#L762)):_
> 
> > ```json
> >                     "keys": {
> >                         "title": "filter key values",
> >                         "description": "The values used to filter the events",
> > ```
> 
> WDYT about adding an example here, e.g. add "the filter [[1,2],[],[3,4]] is interpreted as (key1=1 or key1 = 2) and (key3=3 or key3=4)"?

The openrpc specification does have an `method.examples` property for exactly this (https://spec.open-rpc.org/#method-object).

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @ArielElp, and @Mirko-von-Leipzig)

___
*[`api/starknet_api_openrpc.json` line 762 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-NCFIKAH7L24h3I_fOi8:-NCFSEbn9W7yrHSwxfIi:btpxb44) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/60b87d442ffb7500229808d158b6211fc2d9ae9f/api/starknet_api_openrpc.json#L762)):*
<details><summary><i>Previously, Mirko-von-Leipzig (Mirko von Leipzig) wrote…</i></summary><blockquote>

The openrpc specification does have an `method.examples` property for exactly this (https://spec.open-rpc.org/#method-object).
</blockquote></details>

yes, but then we go into providing a whole example for the whole call.
isn't it better to document this separately (which I plan to do)?

**Comment by Mirko-von-Leipzig** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @ArielElp, and @Mirko-von-Leipzig)
> 
> _[`api/starknet_api_openrpc.json` line 762 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-NCFIKAH7L24h3I_fOi8:-NCFSEbn9W7yrHSwxfIi:btpxb44) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/60b87d442ffb7500229808d158b6211fc2d9ae9f/api/starknet_api_openrpc.json#L762)):_
> Previously, Mirko-von-Leipzig (Mirko von Leipzig) wrote…
> 
> yes, but then we go into providing a whole example for the whole call. isn't it better to document this separately (which I plan to do)?

Yeah that's probably better then - missed that you just wanted to demonstrate the `key` property.

An alternative would be specifying another component for it; which also allows linking in examples, but that seems a bit much just for that.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-:-NCUEyqTEEWPqW-XkLV1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/55#-:-NCUFH3J-bSd1V80liBl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Pull request merged**
