### PR TITLE
fix receipt and pending receipt schema

### PR DESCRIPTION
**Pull request by ShahakShama**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)

### CODE REVIEW

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-NroVg7PCCS8CwDwx_jY:-NroVg7PCCS8CwDwx_jZ:bvllu39) (no related file):*
Can you explain in high level what are the changes?

___

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`api/starknet_api_openrpc.json` line 383 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-Ns2EIDK0JpSMu2OLxXy:-Ns2EIDK0JpSMu2OLxXz:b-dgykhz) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/b1da75cc579e3e9095bcfe12fbb09a36989045de/api/starknet_api_openrpc.json#L383)):*
> ```JSON
>             "result": {
>                 "name": "result",
>                 "schema": {
> ```

Add a description around here that specifies that the former should be returned for txs not in the pending block and the latter is only for txs in the pending block
___
*[`api/starknet_api_openrpc.json` line 1444 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-Ns2DeSAEiwsdY0ET-uV:-Ns2DeSAEiwsdY0ET-uW:b-6vmpnb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/b1da75cc579e3e9095bcfe12fbb09a36989045de/api/starknet_api_openrpc.json#L1444)):*
> ```JSON
>                 ]
>             },
>             "PENDING_BLOCK_BODY_WITH_RECEIPTS": {
> ```

If the entire purpose of PENDING_TXN_RECEIPT after this PR is to hardcode the finality status, then I suggest removing all the PENDING_TXN_RECEIPTS related objects, and remove PENDING_BLOCK_BODY_WITH_RECEIPTS. I think everyone is much cleaner with your TXN_RECEIPT and TXN_RECEIPT_WITH_BLOCK_INFO, where get txn receipts returns one of them and getBlockWithReceipts returns the former (regardless of pending/non-pending block)

**Review by ShahakShama — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-NroVg7PCCS8CwDwx_jY:-Ns2ZBXy1LtfPL98lGtu:b1vme3f) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you explain in high level what are the changes?
</blockquote></details>

Mainly fixing bugs in the schema of receipts and making it more defined

___
___
*[`api/starknet_api_openrpc.json` line 383 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-Ns2EIDK0JpSMu2OLxXy:-Ns2ZAa2DQdc_EsPOGWZ:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/b1da75cc579e3e9095bcfe12fbb09a36989045de/api/starknet_api_openrpc.json#L383)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Add a description around here that specifies that the former should be returned for txs not in the pending block and the latter is only for txs in the pending block
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1444 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-Ns2DeSAEiwsdY0ET-uV:-Ns2Z6S9-75MJebxGCYv:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/b1da75cc579e3e9095bcfe12fbb09a36989045de/api/starknet_api_openrpc.json#L1444)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

If the entire purpose of PENDING_TXN_RECEIPT after this PR is to hardcode the finality status, then I suggest removing all the PENDING_TXN_RECEIPTS related objects, and remove PENDING_BLOCK_BODY_WITH_RECEIPTS. I think everyone is much cleaner with your TXN_RECEIPT and TXN_RECEIPT_WITH_BLOCK_INFO, where get txn receipts returns one of them and getBlockWithReceipts returns the former (regardless of pending/non-pending block)
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195#-:-Ns2iaVq47DkAVVLOJpJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

**Review by yair-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)

**Pull request merged**
