### PR TITLE
Fix get block functions and remove get block with receipts

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/16)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/16)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1084 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/16#-N6c-zYN3b-uetG9HbyI:-N6c-zYN3b-uetG9HbyJ:b1h6gbk) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/48ac42cc85b27a699b615ff43b1f3b3898eda505/api/starknet_api_openrpc.json#L1084)):*
> ```JSON
>                 }
>             },
>             "BLOCK_W_TXS_HASHES": {
> ```

BLOCK_W_TX**~S~**_HASHES --> BLOCK_W_TX**N**_HASHES

I think it should be TX*N* hashes, i.e. `BLOCK_W_TXN_HASHES`, or alternatively `BLOCK_W_TX_HASHES`.
The plural form comes from the Hashe*s*.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/16)* status: all files reviewed, 2 unresolved discussions (waiting on @anatgstarkware)

___
*[`api/starknet_api_openrpc.json` line 62 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/16#-N6cLlQy2SheOTDiqi-q:-N6cLlQy2SheOTDiqi-r:bokjnva) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/48ac42cc85b27a699b615ff43b1f3b3898eda505/api/starknet_api_openrpc.json#L62)):*
> ```JSON
>                     "oneOf": [
>                         {
>                             "$ref": "#/components/schemas/BLOCK_W_TXS"
> ```

W --> WITH everywhere

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/16)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 62 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/16#-N6cLlQy2SheOTDiqi-q:-N6cOBCj-Bd3WnYvZHCi:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/48ac42cc85b27a699b615ff43b1f3b3898eda505/api/starknet_api_openrpc.json#L62)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

W --> WITH everywhere
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1084 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/16#-N6c-zYN3b-uetG9HbyI:-N6cOA4XAiY5I0ChPvwz:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/48ac42cc85b27a699b615ff43b1f3b3898eda505/api/starknet_api_openrpc.json#L1084)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

BLOCK_W_TX**~S~**_HASHES --> BLOCK_W_TX**N**_HASHES

I think it should be TX*N* hashes, i.e. `BLOCK_W_TXN_HASHES`, or alternatively `BLOCK_W_TX_HASHES`.
The plural form comes from the Hashe*s*.
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/16#-:-N6gL9xw6pdKq5-lA-yN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)

**Pull request merged**
