### PR TITLE
add pending transaction receipt

### PR DESCRIPTION
**Pull request by lior-stark**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/34)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/34)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1258 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-N7oBwMl-BfuV9JGgNst:-N7oBwMl-BfuV9JGgNsu:bl3gaj2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/26d4d70f264077f8aa1df5dfccd023cf185a3a73/api/starknet_api_openrpc.json#L1258)):*
> ```JSON
>                 ]
>             },
>             "INVOKE_TXN_SPECIFIC_RECEIPT_PROPS": {
> ```

how about naming it INVOKE_TXN_RECEIPT_PROPERTIES?
___
*[`api/starknet_api_openrpc.json` line 1355 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-N7oC8ugCWqcCEsyg9G8:-N7oC8ugCWqcCEsyg9G9:b-lqgfux) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/26d4d70f264077f8aa1df5dfccd023cf185a3a73/api/starknet_api_openrpc.json#L1355)):*
> ```JSON
>                     },
>                     {
>                         "$comment": "Used for deploy and declare transaction receipts",
> ```

I think it's easier to read if we're more explicit about it, i.e. have a PENDING_DEPLOY_TXN_RECEIPT/PENDING_DECLARE_TXN_RECEIPT types that are references to the common pending properties.

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/34)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1258 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-N7oBwMl-BfuV9JGgNst:-N7ohpNSEQRYprGz7Nae:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/26d4d70f264077f8aa1df5dfccd023cf185a3a73/api/starknet_api_openrpc.json#L1258)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

how about naming it INVOKE_TXN_RECEIPT_PROPERTIES?
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1355 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-N7oC8ugCWqcCEsyg9G8:-N7ohrX526TOnsq8u_g-:b-rqllzd) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/26d4d70f264077f8aa1df5dfccd023cf185a3a73/api/starknet_api_openrpc.json#L1355)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think it's easier to read if we're more explicit about it, i.e. have a PENDING_DEPLOY_TXN_RECEIPT/PENDING_DECLARE_TXN_RECEIPT types that are references to the common pending properties. 
</blockquote></details>

yes, that was the initial version. 
but it's really redundant, it's creating two objects that are structured exactly the same, and don't add anything to the schema.
note that I did add a comment here for future readers.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-:-N7p55Qf2cJMzaeDMfGi:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lior-stark)

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/34#-:-N7p69iH8Pt1CNp5sizK:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lior-stark)

**Pull request merged**
