### PR TITLE
Remove redundant 'class_hash' in the array of declared contracts

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53)

### CODE REVIEW

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 872 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/53#-NB6e0wp52VXbHoultz_:-NB6e0wp52VXbHoultza:baqe1oz) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/24d0d895ec0bb29e40e7c63bdc215bcf5de18d7d/api/starknet_api_openrpc.json#L872)):*
> ```JSON
>                                 "type": "array",
>                                 "items": {
>                                     "description": "The hash of a new contract declared as part of the new state",
> ```

in this case, maybe consider changing the name of the field.
maybe something like `declared_contracts_hashes`?

@arielelp , I'm guessing this wasn't communicated to outside partners, do we want this in 0.2.0 or later?

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53#-:-NBCM_Au6-k9HFdCnDVA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

___
*[`api/starknet_api_openrpc.json` line 872 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/53#-NB6e0wp52VXbHoultz_:-NBCMQyN-sftnR7bh2gr:budrtt3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/24d0d895ec0bb29e40e7c63bdc215bcf5de18d7d/api/starknet_api_openrpc.json#L872)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

in this case, maybe consider changing the name of the field.
maybe something like `declared_contracts_hashes`?

@arielelp , I'm guessing this wasn't communicated to outside partners, do we want this in 0.2.0 or later?

</blockquote></details>

let's have it as part of 0.2.0

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53#-:-NBCY5UV-yGgpc-fYs7E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
