### PR TITLE
v0.17.0: declared vs. deployed contracts in diff

### PR DESCRIPTION
**Pull request by lior-stark**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/11)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/11)* status: all files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1102 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/11#-N5j9QRr59cR2E8vrkB2:-N5j9QRr59cR2E8vrkB3:b-t5exyb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a12e282af5c605e5d1b4cffd35dc07d827ba1bdc/api/starknet_api_openrpc.json#L1102)):*
> ```JSON
>                         "$ref": "#/components/schemas/FELT"
>                     },
>                     "contract_hash": {
> ```

let's rename this to class hash

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/11)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1102 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/11#-N5j9QRr59cR2E8vrkB2:-N61tqvb8rjFPWePx4M0:b-kpva6q) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a12e282af5c605e5d1b4cffd35dc07d827ba1bdc/api/starknet_api_openrpc.json#L1102)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

let's rename this to class hash
</blockquote></details>

it's contract class hash.

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 329 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/11#-N6DKis_19ktxm7xgHHd:-N6DTVmS60Sm_BojmJOV:b-tbn3ui) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2e0d3ef47c0ef8ddc235e6faf83c0127bd2ba119/api/starknet_api_openrpc.json#L329)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

why do we add here the ability to pass block_number?
why not at getStorageAt and getClassAt? why not also block_hash?
</blockquote></details>

the idea is that a deployed contract is part of the state, so like asking for other state changes - in a given block, we should be able to ask for the state of a deployed contract in a given point in time.

`getStorageAt` also has a `block_hash` parameter for this.
You're right that theoretically, the same logic applies also to contract _declaration_. So we should probably add it in `getClassAt`.

It can also be by block hash.

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 329 at r4](https://reviewable.io/reviews/starkware-libs/starknet-specs/11#-N6DKis_19ktxm7xgHHd:-N6DV521EgAlospFX6mB:bt9zqmq) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/2e0d3ef47c0ef8ddc235e6faf83c0127bd2ba119/api/starknet_api_openrpc.json#L329)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the idea is that a deployed contract is part of the state, so like asking for other state changes - in a given block, we should be able to ask for the state of a deployed contract in a given point in time.

`getStorageAt` also has a `block_hash` parameter for this.
You're right that theoretically, the same logic applies also to contract _declaration_. So we should probably add it in `getClassAt`.

It can also be by block hash.

</blockquote></details>

@dan-starkware , @anatgstarkware , @spapinistarkware - FYI, because we discussed this.

**Pull request closed without merging**
