### PR TITLE
Liors/sn api v0.12.0

### PR DESCRIPTION
**Pull request by lior-stark**
some refactoring, following [this](https://starkwareindustries.slack.com/archives/D02FND7MEDP/p1654145791584109) discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mwbn36BYvUeGf5_YP:-N4Mwbn36BYvUeGf5_YQ:b-4vmy24) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1078)):*
> ```JSON
>             "COMMON_TXN_PROPERTIES": {
>                 "type": "object",
>                 "properties": {
> ```

add signature
___
*[`api/starknet_api_openrpc.json` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4MsEFD3ecgb9_nOf8R:-N4MsEFEDgu6YBIRztL2:b26k9rp) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1103)):*
> ```JSON
>                         "properties": {
>                             "contract_class": {
>                                 "description": "The contract definition deployed",
> ```

Change to: The class to be declared
___
*[`api/starknet_api_openrpc.json` line 1106 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4MvsWICNNea3SeFkyy:-N4MvsWICNNea3SeFkyz:bwp30me) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1106)):*
> ```JSON
>                                 "$ref": "#/components/schemas/CONTRACT_CLASS"
>                             },
>                             "sender_address": {
> ```

None blocking

Eventually this field, alongside nonce, would be in the common properties, correct?
For invokes, we can't really decode the calldata into the actual function call, so either the above does not hold or function_call would get a little bit weirder (only calldata?) 
___
*[`api/starknet_api_openrpc.json` line 1141 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mtsn_DLwEF7-2BlVw:-N4Mtsn_DLwEF7-2BlVx:b-tk0xtp) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1141)):*
> ```JSON
>                         "$ref": "#/components/schemas/TXN_STATUS"
>                     },
>                     "statusData": {
> ```

what's this? let's remove it if we have no use for it now

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 1078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mwbn36BYvUeGf5_YP:-N4R7bP65O3OMUW9czpa:b-o2hmr9) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1078)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

add signature
</blockquote></details>

you mean the signature should be retrieved for a transaction?

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 1078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mwbn36BYvUeGf5_YP:-N4R7qU32zCkxCI9Jawk:bfibnme) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1078)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

you mean the signature should be retrieved for a transaction?
</blockquote></details>

also, note that `addDeclareTransaction` doesn't have a signature, so this would be inconsistent.

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1103 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4MsEFD3ecgb9_nOf8R:-N4R8C2zB50iSKYtG578:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1103)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Change to: The class to be declared
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1106 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4MvsWICNNea3SeFkyy:-N4R8UOm6zLydfXbnT7A:b5e4ex2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1106)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

None blocking

Eventually this field, alongside nonce, would be in the common properties, correct?
For invokes, we can't really decode the calldata into the actual function call, so either the above does not hold or function_call would get a little bit weirder (only calldata?) 
</blockquote></details>

we might need to factor our the `contract_address` from `FUNCTION_CALL`. Let's discuss.
but I think it's not critical for now.
___
*[`api/starknet_api_openrpc.json` line 1141 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mtsn_DLwEF7-2BlVw:-N4R8bcfEca3LyEA8Jz0:bb7c6s1) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1141)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

what's this? let's remove it if we have no use for it now
</blockquote></details>

as the description says, it's a chance to provide extra information on the status.
for example, why it was rejected/aborted.
I think it could be useful.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mwbn36BYvUeGf5_YP:-N4aTSfW7f0WvjMPX2mz:blrmyxl) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1078)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

also, note that `addDeclareTransaction` doesn't have a signature, so this would be inconsistent.
</blockquote></details>

Eventually it will have, fees will have to be paid somehow
Internally we have a signature field, it's just defaulted to []

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-N4Mwbn36BYvUeGf5_YP:-N4aeIb6AgP55HzY-8_Q:b-ipr7cc) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/a402c3409769f7c07be899442145cf2b758053c3/api/starknet_api_openrpc.json#L1078)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Eventually it will have, fees will have to be paid somehow
Internally we have a signature field, it's just defaulted to [] 
</blockquote></details>

added.
I wonder if maybe we should already add signature to `addDeclareTransaction`

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-:-N4vD7VEAdL-SLyY-_gz:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lior-stark)

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5#-:-N4vpQ4LA_6WEK9AmdIU:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lior-stark)

**Review by lior-stark — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Pull request merged**
