### PR TITLE
Fix `keys` ref in `starknet_subscribeEvents`

### PR DESCRIPTION
**Pull request by franciszekjob**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/243)

### CODE REVIEW

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/243#-:-OBOzcqp1RXZoPrYt14a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @franciszekjob)

**Comment by amanusk** [comment]
Can you please rebase this on top of latest v0.8.0, just so CI would pass :)

**Comment by ArielElp** [comment]
it's the updated validation script failing actually, no merge conflicts

**Comment by franciszekjob** [comment]
@ArielElp yup, for some reason the validation fails. However, it's not related with the change, same [CI fail](https://github.com/starkware-libs/starknet-specs/actions/runs/11592704547/job/32275168096) happened in other PR from what I see.

**Comment by amanusk** [comment]
This PR: https://github.com/starkware-libs/starknet-specs/pull/235
Introduced a fix to the validation script and to the spec.
Since your PR was suggested before this fix was introduced, the CI is running on your codebase, and not the codebase after the merge.
There are no conflicts for merging, but the CI is still failing. The PR you linked failed for the same reason.

**Review by ArielElp — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @franciszekjob)

**Pull request merged**
