### PR TITLE
add invoke txn v1

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
if there's a new kind of invoke transaction (not sure what it is), don't we need it in the write API as well?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-:-N8sRgXhAn2mAhKCGmEx:b3nrd63)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N8sQoW2-hsNP7yPI_Ez:brtdtfd) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
> ```JSON
>             "INVOKE_TXN_V1": {
>                 "title": "version 1 invoke transaction",
>                 "description": "initiates a transaction from a given account",
> ```

why the distinction here?
`FUNCTION_CALL` also includes the address and call data? 
why does this need to be repeated here?
and don't you also need the entry point selector?
___
*[`api/starknet_api_openrpc.json` line 1268 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sPe2461Wq25nTz6N9:-N8sPe2461Wq25nTz6NA:bob2ucp) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1268)):*
> ```JSON
>             "INVOKE_TXN": {
>                 "title": "Initiate a transaction from an account",
>                 "properties": {
> ```

there should be a 
```
 "type" : "object" 
```
here.

you want to have a property names `account_address`, with a value of an object that has the common transaction properties?
___
*[`api/starknet_api_openrpc.json` line 1273 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQ60s2FuppVl86xA_:-N8sQ60s2FuppVl86xAa:bg2aya7) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1273)):*
> ```JSON
>                     }
>                 },
>                 "oneOf": [
> ```

this contradicts the definition of the object above.
did you mean this to have the common properties and then one of these two?

**Review by ArielElp — COMMENTED** [review]
good call, will add

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-:-N8sak4F6X55rinUqVF1:b95z7lv)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @ArielElp, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N8saZmh0IkjkwhrrPVJ:bcx48c3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why the distinction here?
`FUNCTION_CALL` also includes the address and call data? 
why does this need to be repeated here?
and don't you also need the entry point selector?


</blockquote></details>

v1 txs don't have selectors, so it's distinct from function call (the flow is always validate->execute)
___
*[`api/starknet_api_openrpc.json` line 1273 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQ60s2FuppVl86xA_:-N8saRoh5xDe_8UCEyLd:b-3zxj3f) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1273)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this contradicts the definition of the object above.
did you mean this to have the common properties and then one of these two?

</blockquote></details>

yes, not sure how to write that

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N8w-jEJ4JOmIOvTiFbc:b-n5b2za) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

v1 txs don't have selectors, so it's distinct from function call (the flow is always validate->execute)
</blockquote></details>

ok, but then the call data includes the selector the execute will call, no?
the call data isn't only the parameters passed to the function.
___
*[`api/starknet_api_openrpc.json` line 1273 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQ60s2FuppVl86xA_:-N8w014CAaINgurp0gSY:bulhvyb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1273)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

yes, not sure how to write that
</blockquote></details>

I think it should be something like:
```

"INVOKE_TXN" : {
  allOf : [
    { $ref : ".../COMMON_TXN_PROPERTIES" },
    {
      oneOf : [
        { $ref : ".../INVOKE_TXN_V0" },
        { $ref : ".../INVOKE_TXN_V1" }
      ]
    }
  ]
  
}

```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N8y6icPDVBDZvBp1cVh:barkpka) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

ok, but then the call data includes the selector the execute will call, no?
the call data isn't only the parameters passed to the function.
</blockquote></details>

Yes, the calldata will include the "real" selector, but this isn't part of the protocol.  The transaction does not have a selector member (consider a stupid account that only calls a fixed function at a specific contract, so there's no need to specify a selector).
___
*[`api/starknet_api_openrpc.json` line 1268 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sPe2461Wq25nTz6N9:-N8y6abvCB4O-jdH2-UF:b-jw63xf) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1268)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

there should be a 
```
 "type" : "object" 
```
here.

you want to have a property names `account_address`, with a value of an object that has the common transaction properties?
</blockquote></details>

fixed, sorry for that nonsense
___
*[`api/starknet_api_openrpc.json` line 1273 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQ60s2FuppVl86xA_:-N8y6YD3-AL9oZVMMca5:b-3b3r3t) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1273)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

I think it should be something like:
```

"INVOKE_TXN" : {
  allOf : [
    { $ref : ".../COMMON_TXN_PROPERTIES" },
    {
      oneOf : [
        { $ref : ".../INVOKE_TXN_V0" },
        { $ref : ".../INVOKE_TXN_V1" }
      ]
    }
  ]
  
}

```
</blockquote></details>

Makes sense, corrected

**Review by ArielElp — COMMENTED** [review]
Added the type BROADCASTED_INVOKE_TXN, whose schema is what is expected by sequencers (currently our gateway). This type is used both in the write API and estimate_fee (previously argument scheme for estimate fee didn't make a lot of sense as e.g. transaction_hash/type were also part of it).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-:-N8zfEeN2L-tnu9cGFO5:b-1e0gqe)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N90AZVx0bNbAiU4ZpXr:bgdflss) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Yes, the calldata will include the "real" selector, but this isn't part of the protocol.  The transaction does not have a selector member (consider a stupid account that only calls a fixed function at a specific contract, so there's no need to specify a selector).
</blockquote></details>

ok, in that case i think the description of the `calldata` should mention that - the common case (that it includes the selector).
___
*[`api/starknet_api_openrpc.json` line 1297 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N90AqWj5cuiMkkJkNi5:-N90AqWj5cuiMkkJkNi6:b-k1a0g3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7eab03b257cb7b8f1f7012d25b4dbdd4142c0f80/api/starknet_api_openrpc.json#L1297)):*
> ```JSON
>                 ]
>             },
>             "BROADCASTED_INVOKE_TXN": {
> ```

it's only here because you use it in COMMON_TXN_PROPERTIES?
___
*[`api/starknet_write_api.json` line 19 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N90B-WS9qVZG7Q45Zx0:-N90B-WS9qVZG7Q45Zx1:b9tnr5l) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7eab03b257cb7b8f1f7012d25b4dbdd4142c0f80/api/starknet_write_api.json#L19)):*
> ```JSON
>                     "required": true,
>                     "schema": {
>                         "$ref": "#/components/schemas/BROADCASTED_INVOKE_TXN"
> ```

i can't find it in this file - is this reference correct?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1252 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N8sQoW2-hsNP7yPI_Ey:-N90HoEmCNwz155QRKhj:b7bsaor) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/ef90648684db5349666d82810a9837161df566d9/api/starknet_api_openrpc.json#L1252)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

ok, in that case i think the description of the `calldata` should mention that - the common case (that it includes the selector).
</blockquote></details>

edited the description
___
*[`api/starknet_api_openrpc.json` line 1297 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N90AqWj5cuiMkkJkNi5:-N90FvVr5oRTc5X5eV84:bqacaeh) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7eab03b257cb7b8f1f7012d25b4dbdd4142c0f80/api/starknet_api_openrpc.json#L1297)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

it's only here because you use it in COMMON_TXN_PROPERTIES?
</blockquote></details>

because I use it in estimateFee
___
*[`api/starknet_write_api.json` line 19 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N90B-WS9qVZG7Q45Zx0:-N90GQ8g2Pt_Hw_N68V6:b-t34kmh) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7eab03b257cb7b8f1f7012d25b4dbdd4142c0f80/api/starknet_write_api.json#L19)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

i can't find it in this file - is this reference correct?
</blockquote></details>

added a reference under components

**Review by lior-stark — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @anatgstarkware, @ArielElp, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1161 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N9RHsWy4rmRBC5tY1Jd:-N9RHsWz-fgwMSkNLE7R:beugfgg) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7e629385b6b5d0fb526d2019f88cd80b091ab714/api/starknet_api_openrpc.json#L1161)):*
> ```JSON
>                 }
>             },
>             "BROADCASTED_TXN_COMMON_PROPERTIES": {
> ```

why no transaction type in this case?

also, why "BROADCASTED" transaction?
isn't this basically a transaction that's "waiting in the pool" (if we had a pool)?
so isn't this actually a _pending_ transaction?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1161 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-N9RHsWy4rmRBC5tY1Jd:-N9Rzgd_402rzswv3Om0:bf32vh8) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/7e629385b6b5d0fb526d2019f88cd80b091ab714/api/starknet_api_openrpc.json#L1161)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why no transaction type in this case?

also, why "BROADCASTED" transaction?
isn't this basically a transaction that's "waiting in the pool" (if we had a pool)?
so isn't this actually a _pending_ transaction?
</blockquote></details>

added type

"broadcasted" in the sense that this is what the end user sends. Pending sounds confusing (it suggests relation to the pending block, which is not exactly our analog of mempool as the tx is already executed at this point). I think broadcasted is a better fit than pending, as it doesn't say anything about the status of the transaction (it may even be completely ignore by sequencers, e.g. improperly signed).

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/42#-:-N9Yrigb8Oi2xqsP8V8F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
