### PR TITLE
separate address and hashes from other felts

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/66)

### CODE REVIEW

**Comment by anatgstarkware** [comment]
*[`api/starknet_api_openrpc.json` line 929 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/66#-NKTA3dBE8JOx1cIxbRC:-NKTA3dBE8JOx1cIxbRD:b6c5866) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/daffa2a1ae8b89744b61e25499359517ee58a76e/api/starknet_api_openrpc.json#L929)):*
> ```JSON
>                 "title": "A transaction's hash"
>             },
>             "ADDRESS_OR_HASH_FELT": {
> ```

Can we separate the addresses and the hashes?

**Comment by anatgstarkware** [comment]
*[`api/starknet_api_openrpc.json` line 931 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/66#-NKTAFOL9s5Egw15WEUx:-NKTAFOMC82DN7SDINFF:b23s2fs) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/daffa2a1ae8b89744b61e25499359517ee58a76e/api/starknet_api_openrpc.json#L931)):*
> ```JSON
>             "ADDRESS_OR_HASH_FELT": {
>                 "type": "string",
>                 "title": "Field element",
> ```

Do you want to update the title and description as well?

**Review by anatgstarkware — COMMENTED** [review]
Do you want to update the version of the document?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/66#-:-NKTAPXH1zp40rMenpbP:b-dv83l8)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ArielElp and @dan-starkware)

**Comment by Mirko-von-Leipzig** [comment]
What is the benefit of distinguishing between these? I understand that these are likely to use most of the bits in the field as they are usually truely random, but surely there is no difference to be made in (de)serialisation?

**Comment by eschnou** [comment]
The issue with this current suggestion is that addresses in dedicated fields will have a different format than addresses in events/calldata. In addition, the lack of type data in events (everything is felt, no ‘address’ native type), makes it harder to index events by addresses. So; in our opinion, this would be a change in the wrong direction. Standardizing felt representation would be good enough.

**Pull request closed without merging**
