### PR TITLE
Remove block response scope options

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnZHx8jujMYV8qI0A:-N5nnZHx8jujMYV8qI0B:b2uqdu2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L4)):*
> ```JSON
>     "openrpc": "1.0.0-rc1",
>     "info": {
>         "version": "0.16.0",
> ```

this should actually be 0.18.0, we already have 0.17.0 in PR.
___
*[`api/starknet_api_openrpc.json` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nn2YgEjYS4O386Gij:-N5nn2YgEjYS4O386Gik:b-boz1fo) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L44)):*
> ```JSON
>         },
>         {
>             "name": "starknet_getBlockByHash_withTransactions",
> ```

the naming here diverges from the pattern used everywhere else.
why not named it `starknet_getBlockByHashWithTransactions`?
___
*[`api/starknet_api_openrpc.json` line 45 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnDgH8n3UjIfVfZUj:-N5nnDgH8n3UjIfVfZUk:b-hvqpi5) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L45)):*
> ```JSON
>         {
>             "name": "starknet_getBlockByHash_withTransactions",
>             "summary": "Get block information given the block id",
> ```

we should probably add that it includes also the txn information.
___
*[`api/starknet_api_openrpc.json` line 62 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5no-OA6NXIxJdZNeLH:-N5no-OA6NXIxJdZNeLI:bod0w3t) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L62)):*
> ```JSON
>                     "oneOf": [
>                         {
>                             "$ref": "#/components/schemas/BLOCK"
> ```

it's weird that all these methods return the same return type.

the distinction is currently in the BLOCK_BODY type, but isn't the whole point of this is that we have different types returned from each function?

So I'm thinking we should also have distinct types, something like `BLOCK_BODY`, `FULL_BLOCK_BODY` and `FULL_BLOCK_BODY_W_RECEIPTS`

wdyt?

(same for the XXXByNumber set of methods below)
___
*[`api/starknet_api_openrpc.json` line 77 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5noNlc90t42phOVqTX:-N5noNldEw6hjVlto2AW:b8aw1sr) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L77)):*
> ```JSON
>         },
>         {
>             "name": "starknet_getBlockByHash_withTransactionsAndReceipts",
> ```

also here the naming.
___
*[`api/starknet_api_openrpc.json` line 78 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnPHsCO1cxWjS-cVb:-N5nnPHsCO1cxWjS-cVc:b-o0w3zj) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L78)):*
> ```JSON
>         {
>             "name": "starknet_getBlockByHash_withTransactionsAndReceipts",
>             "summary": "Get block information given the block id",
> ```

with transactions and receipts, right?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnZHx8jujMYV8qI0A:-N5oFcu64xiHuo0Vnb4c:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L4)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this should actually be 0.18.0, we already have 0.17.0 in PR.
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 44 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nn2YgEjYS4O386Gij:-N5oG8es8V9ShHl0mtIj:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L44)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the naming here diverges from the pattern used everywhere else.
why not named it `starknet_getBlockByHashWithTransactions`?
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 45 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnDgH8n3UjIfVfZUj:-N5oGngP3mRDcL9IcoYC:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L45)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

we should probably add that it includes also the txn information.
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 62 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5no-OA6NXIxJdZNeLH:-N5oYxjk-dkJF0wyus_T:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L62)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

it's weird that all these methods return the same return type.

the distinction is currently in the BLOCK_BODY type, but isn't the whole point of this is that we have different types returned from each function?

So I'm thinking we should also have distinct types, something like `BLOCK_BODY`, `FULL_BLOCK_BODY` and `FULL_BLOCK_BODY_W_RECEIPTS`

wdyt?

(same for the XXXByNumber set of methods below)
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 77 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5noNlc90t42phOVqTX:-N5oYymJ56hOjX-M8t93:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L77)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

also here the naming.
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 78 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N5nnPHsCO1cxWjS-cVb:-N5oYznOCRSNDSveH6HO:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/e1d1397e5ff9deffa0a04ff54d8f737406169cdb/api/starknet_api_openrpc.json#L78)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

with transactions and receipts, right?
</blockquote></details>

Done.

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: all files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @ArielElp, and @bbrandtom)

___
*[`api/starknet_api_openrpc.json` line 1181 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N61uYJP17n3c4gFwapG:-N61uYJP17n3c4gFwapH:b-xug0g0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/93c58b621ced81d87db9af6a99f8156d3a86b9f8/api/starknet_api_openrpc.json#L1181)):*
> ```JSON
>                 "allOf": [
>                     {
>                         "status": {
> ```

 I wonder if the status should be out of the definition of the block.
it could be in the return value from `getBlockXXX`, but it's not as clean if it's in the block object itself.
Mainly because the block definition is independent from its status.

@anatgstarkware , @arielelp : wdyt?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1181 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-N61uYJP17n3c4gFwapG:-N63HcO_2-NvMR4wnCDE:bdb9d3x) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/93c58b621ced81d87db9af6a99f8156d3a86b9f8/api/starknet_api_openrpc.json#L1181)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

 I wonder if the status should be out of the definition of the block.
it could be in the return value from `getBlockXXX`, but it's not as clean if it's in the block object itself.
Mainly because the block definition is independent from its status.

@anatgstarkware , @arielelp : wdyt?
</blockquote></details>

Can we maybe postpone this discussion to a different PR?

**Review by lior-stark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @lior-stark)

**Review by lior-stark — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13#-:-N6CAJ4zDAPAHDZWGk2g:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @lior-stark)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp and @bbrandtom)

**Pull request merged**
