### PR TITLE
v0.20.0: add deploy transaction

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)

### CODE REVIEW

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bbrandtom and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6bz5RZ--gge8DITe2u:-N6bz5RZ--gge8DITe2v:blwaps0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/d96fd7bbaf8508e614bfb29164c37be5977d4b84/api/starknet_api_openrpc.json#L4)):*
> ```JSON
>     "openrpc": "1.0.0-rc1",
>     "info": {
>         "version": "0.19.0",
> ```

Please change the version to 0.20.0
PR#14 was version 0.19.0

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bbrandtom and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 4 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6bz5RZ--gge8DITe2u:-N6c0YmF46sKhWospcrK:bb6un1j) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/d96fd7bbaf8508e614bfb29164c37be5977d4b84/api/starknet_api_openrpc.json#L4)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

Please change the version to 0.20.0
PR#14 was version 0.19.0
</blockquote></details>

Done

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1414 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBRPWAAVMfbOQcb9E:-N6cBRPWAAVMfbOQcb9F:undefined) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1414)):*
> ```JSON
>                         "constructor_calldata": {
>                             "type": "array",
>                             "description": "The parameters passed to the function",
> ```





_Suggestion:_
```JSON
constructor
```
___
*[`api/starknet_api_openrpc.json` line 1419 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBIdE8AkJda_6mK9m:-N6cBIdF5TgU2u09nwdl:bo4mtq2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1419)):*
> ```JSON
>                             }
>                         },
>                         "sender_address": {
> ```

I don't think we have a sender for deploy tx
___
*[`api/starknet_api_openrpc.json` line 1420 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBKrO7GZT9d3o_71B:-N6cBKrO7GZT9d3o_71C:b-aemnu1) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1420)):*
> ```JSON
>                         },
>                         "sender_address": {
>                             "description": "The address of the account contract sending the declaration transaction",
> ```

seems like the description is for declare tx

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bbrandtom and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1414 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBRPWAAVMfbOQcb9E:-N6cHpf82NMkXuXLMxHS:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1414)):*
> ```JSON
>                         "constructor_calldata": {
>                             "type": "array",
>                             "description": "The parameters passed to the function",
> ```

Done.
___
*[`api/starknet_api_openrpc.json` line 1419 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBIdE8AkJda_6mK9m:-N6cHoxm67-eyBPa7poa:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1419)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I don't think we have a sender for deploy tx
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1420 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-N6cBKrO7GZT9d3o_71B:-N6cHpEC9htHrwpDWPqW:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/6f00c4c2bc23f2f18530fbb585b3bc00eab5fb39/api/starknet_api_openrpc.json#L1420)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

seems like the description is for declare tx
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/15#-:-N6cy1ju1rRsm-iocFlE:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lior-stark)

**Pull request merged**
