### PR TITLE
add abi to class

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1566 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tjaVE1fjxy-39dqEI:-N8tjaVE1fjxy-39dqEJ:b-kgzcal) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1566)):*
> ```JSON
>                 ]
>             },
>             "STRUCT_ABI_ENTRY": {
> ```

properties of an object should appear under `properties`, i.e.

```
  "STRUCT_ABI_ENTRY": {
    "type" : "object",
    "properties" : {
      "name" : { ... },
      "size" : {
        "type" : "integer",
        "minimum" : 0
      }
    }
 }
```
___
*[`api/starknet_api_openrpc.json` line 1567 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tk9cGAucJWRLgBkjg:-N8tk9cGAucJWRLgBkjh:b-7jpai3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1567)):*
> ```JSON
>             },
>             "STRUCT_ABI_ENTRY": {
>                 "type": {
> ```

probably best not to have a `type` named property, because it's kind of a reserved word.
not sure if it's legal or not, but it can be confusing imo.
___
*[`api/starknet_api_openrpc.json` line 1569 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8truqR-7d34wYitoeE:-N8truqR-7d34wYitoeF:b-gm68dw) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1569)):*
> ```JSON
>                 "type": {
>                     "schema": {
>                         "$ref": "#/components/schemas/ABI_ITEM_TYPE"
> ```

isn't this always a `struct` ?
___
*[`api/starknet_api_openrpc.json` line 1573 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tk6RyD7JCBzTi_1wf:-N8tk6RyD7JCBzTi_1wg:ba6r30a) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1573)):*
> ```JSON
>                 },
>                 "name": {
>                     "description": "The event name",
> ```

the event name or the struct name?
___
*[`api/starknet_api_openrpc.json` line 1586 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8ts4yi0FHmlazLb_5p:-N8ts4yi0FHmlazLb_5q:bdswm2i) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1586)):*
> ```JSON
>                 }
>             },
>             "STRUCT_MEMBER": {
> ```

isn't this basically a typed symbol (what you call below FUNCTION_SIGNATURE_ITEM) + offset?
so define it like:
```
"STRUCT_MEMBER" : {
  allOf : [
    { $ref : ".../FUNCTION_SIGNATURE_ITEM" },
    {
      "type" : "object",
      "properties" : {
        "offset" : {
          $ref : " ..../FELT"
        }
      }
    }
  ]
}
```
___
*[`api/starknet_api_openrpc.json` line 1595 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tsdkr9gto-t-rMieD:-N8tsdkr9gto-t-rMieE:beppk74) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1595)):*
> ```JSON
>                     "offset": {
>                         "description": "offset of this property within the struct",
>                         "type": "integer"
> ```

shouldn't this be a FELT?
or we imply here that it's a small enough so it can be converted to FELT?
___
*[`api/starknet_api_openrpc.json` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkNYt8YDJtHbmcVE7:-N8tkNYt8YDJtHbmcVE8:b-yk7dwb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1599)):*
> ```JSON
>                     "type": {
>                         "description": "the property's type",
>                         "type": "string"
> ```

there's no predefined list of cairo types we can refer to?
even as a comment (`$comment`) here?
___
*[`api/starknet_api_openrpc.json` line 1606 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkYCeA8qHO5iX_EaP:-N8tkYCeA8qHO5iX_EaQ:bjww9xn) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1606)):*
> ```JSON
>                 "type": {
>                     "schema": {
>                         "$ref": "#/components/schemas/ABI_ITEM_TYPE"
> ```

isn't this always `event` in this case?
___
*[`api/starknet_api_openrpc.json` line 1613 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkyVS7Yrqm8AFNQL3:-N8tkoYy0wqHEXcINlHx:bevwcup) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1613)):*
> ```JSON
>                     "type": "string"
>                 },
>                 "keys": {
> ```

are these a subset of `data`?
___
*[`api/starknet_api_openrpc.json` line 1616 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkjXyChhoW2XR8SmO:-N8tkjXyChhoW2XR8SmP:bc3yz78) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1616)):*
> ```JSON
>                     "type": "array",
>                     "items": {
>                         "$ref": "#/components/schemas/FUNCTION_SIGNATURE_ITEM"
> ```

so this is actually a declared parameter?
why not call it something like "DECLARED_PARAM" or simply a "TYPED_SYMBOL"?
___
*[`api/starknet_api_openrpc.json` line 1647 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8trRVs0cKeq1knU4ms:-N8trRVs0cKeq1knU4mt:b-sxznfb) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1647)):*
> ```JSON
>                         "type": "array",
>                         "items": {
>                             "$ref": "#/components/schemas/FUNCTION_SIGNATURE_ITEM"
> ```

outputs also have names?
___
*[`api/starknet_api_openrpc.json` line 1652 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tl1vcAENV-pP5yUtq:-N8tl1vcAENV-pP5yUtr:biuzfe8) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1652)):*
> ```JSON
>                 }
>             },
>             "FUNCTION_SIGNATURE_ITEM": {
> ```

from its usage, this should probably be called something like "TYPED_SYMBOL" or something similar.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1566 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tjaVE1fjxy-39dqEI:-N8xOuYuCV_9vPYPQclZ:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1566)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

properties of an object should appear under `properties`, i.e.

```
  "STRUCT_ABI_ENTRY": {
    "type" : "object",
    "properties" : {
      "name" : { ... },
      "size" : {
        "type" : "integer",
        "minimum" : 0
      }
    }
 }
```


</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 1567 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tk9cGAucJWRLgBkjg:-N8xOx4j56V3bmAFSluW:b-8d9xw3) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1567)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

probably best not to have a `type` named property, because it's kind of a reserved word.
not sure if it's legal or not, but it can be confusing imo.
</blockquote></details>

I want to be consistent with the property name on the gateways (to avoid reworking abis to match the feeder gateway spec), and we use "type".
___
*[`api/starknet_api_openrpc.json` line 1569 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8truqR-7d34wYitoeE:-N8xPMP7Dft-Vt2wyuqM:b-3wncop) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1569)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

isn't this always a `struct` ?
</blockquote></details>

yes, but it's needed to distinguish this entry (like transaction type in common tx properties), I can add COMMON_ABI_ENTRY_PROPERTIES but it will only consist of type

additionally, it's matching to our gateways
___
*[`api/starknet_api_openrpc.json` line 1573 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tk6RyD7JCBzTi_1wf:-N8xPwfr1pI9G2N38Jwa:b-7ql1td) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1573)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the event name or the struct name?
</blockquote></details>

fixed
___
*[`api/starknet_api_openrpc.json` line 1586 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8ts4yi0FHmlazLb_5p:-N8xQOAg0A_aFBhWd3_Z:b-5ap0tt) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1586)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

isn't this basically a typed symbol (what you call below FUNCTION_SIGNATURE_ITEM) + offset?
so define it like:
```
"STRUCT_MEMBER" : {
  allOf : [
    { $ref : ".../FUNCTION_SIGNATURE_ITEM" },
    {
      "type" : "object",
      "properties" : {
        "offset" : {
          $ref : " ..../FELT"
        }
      }
    }
  ]
}
```



</blockquote></details>

Ok, renamed this to TYPED_PARAMETER so it won't be confusing
___
*[`api/starknet_api_openrpc.json` line 1595 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tsdkr9gto-t-rMieD:-N8xRLSR1TAxI2BgojU_:b-1eykcq) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1595)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

shouldn't this be a FELT?
or we imply here that it's a small enough so it can be converted to FELT?
</blockquote></details>

technically you deduce a memory address from it so it should be a felt, but we're talking about a type that needs to be compiled so the offset is much smaller than the field size
___
*[`api/starknet_api_openrpc.json` line 1599 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkNYt8YDJtHbmcVE7:-N8xS8cg5pE7vs3Yj0ah:b-av3id5) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1599)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

there's no predefined list of cairo types we can refer to?
even as a comment (`$comment`) here?
</blockquote></details>

felt/felt* but it can also be a struct/struct* that was defined in the contract, I'm not very worried about this because this will probably change with Sierra in ~4 months
___
*[`api/starknet_api_openrpc.json` line 1606 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkYCeA8qHO5iX_EaP:-N8xSNB160p6s6eL73HH:be9nw2s) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1606)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

isn't this always `event` in this case?
</blockquote></details>

yes, same as struct, analogous to tx type in the common properties (since it's only one property I didn't move it under common)
___
*[`api/starknet_api_openrpc.json` line 1613 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkyVS7Yrqm8AFNQL3:-N8xSaNa3CTET58rJRN8:bhoxeye) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1613)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

are these a subset of `data`?
</blockquote></details>

No, a StarkNet event is defined by a list of keys and a list of data, those are not coupled in any way
___
*[`api/starknet_api_openrpc.json` line 1616 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tkjXyChhoW2XR8SmO:-N8xSmPs7QAinjlGs_ws:b70fz4) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1616)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so this is actually a declared parameter?
why not call it something like "DECLARED_PARAM" or simply a "TYPED_SYMBOL"?
</blockquote></details>

changed to TYPED_PARAMETER
___
*[`api/starknet_api_openrpc.json` line 1647 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8trRVs0cKeq1knU4ms:-N8xSooF1QMbnxkFhQad:b2nign6) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1647)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

outputs also have names?
</blockquote></details>

yes
___
*[`api/starknet_api_openrpc.json` line 1652 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tl1vcAENV-pP5yUtq:-N8xSw3160ftXAdsiyxo:b-n9tkhd) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1652)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

from its usage, this should probably be called something like "TYPED_SYMBOL" or something similar.
</blockquote></details>

changed

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1569 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8truqR-7d34wYitoeE:-N90EJEUBBUwEax-npAQ:bnvd7us) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1569)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

yes, but it's needed to distinguish this entry (like transaction type in common tx properties), I can add COMMON_ABI_ENTRY_PROPERTIES but it will only consist of type

additionally, it's matching to our gateways
</blockquote></details>

we can enforce a constant value to be accepted here.
the trick is to use a json schema that is an enum of a single value.
for example
```
"STRUCT_ABI_TYPE" : {
  "type" : string,
  enum : ["struct"]
}
```
(same for event type etc.)
and then your `ABI_ITEM_TYPE` will be a combination (I guess `oneOf`) of these types.

This can be a bit cumbersome maybe, but it's strict and explicit.

At the very least the expected values should be documented (with a `$comment`).

wdyt?
___
*[`api/starknet_api_openrpc.json` line 1595 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8tsdkr9gto-t-rMieD:-N90D8QW2UXB95NRkjxf:b9zl3ka) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1595)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

technically you deduce a memory address from it so it should be a felt, but we're talking about a type that needs to be compiled so the offset is much smaller than the field size
</blockquote></details>

yes, i realize that.
so there's an implicit conversion here to FELT.

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ArielElp and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1569 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N8truqR-7d34wYitoeE:-N90gMU36iJ1AbVMAqkt:b-vpmozv) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/421c3a8019a58a51c12fba052a591a3ec101799e/api/starknet_api_openrpc.json#L1569)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

we can enforce a constant value to be accepted here.
the trick is to use a json schema that is an enum of a single value.
for example
```
"STRUCT_ABI_TYPE" : {
  "type" : string,
  enum : ["struct"]
}
```
(same for event type etc.)
and then your `ABI_ITEM_TYPE` will be a combination (I guess `oneOf`) of these types.

This can be a bit cumbersome maybe, but it's strict and explicit.

At the very least the expected values should be documented (with a `$comment`).

wdyt?
</blockquote></details>

Changed it to be more explicit, now I have no more use for ABI_ITEM_TYPE so I removed it.

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1587 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N9RJlWJChQUqilQsAim:-N9RJlWJChQUqilQsAin:bvlddio) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4fdf0c7993593afc666290b740471421a72cdfb1/api/starknet_api_openrpc.json#L1587)):*
> ```JSON
>                     },
>                     "size": {
>                         "type": "integer"
> ```

add `"minimum" : 0` ?
I assume it's non-negative
___
*[`api/starknet_api_openrpc.json` line 1614 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N9RKCsk7JIuD2eQTSRE:-N9RKCsk7JIuD2eQTSRF:b-wvkght) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4fdf0c7993593afc666290b740471421a72cdfb1/api/starknet_api_openrpc.json#L1614)):*
> ```JSON
>                 ]
>             },
>             "EVENT_ABI_ENTRY": {
> ```

the object properties should be under `properties`.
so it should be:
```
EVENT_ABI_ENTRY : {
  "type" : "object",
  "properties" : {
    "type" : { ... },
   "name" : {...}
   ...
  }
}
```

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1587 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N9RJlWJChQUqilQsAim:-N9S0NJrAy_32gcuqTBo:bsyw6k) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4fdf0c7993593afc666290b740471421a72cdfb1/api/starknet_api_openrpc.json#L1587)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

add `"minimum" : 0` ?
I assume it's non-negative
</blockquote></details>

add minimum 1 (we need at least one member)
___
*[`api/starknet_api_openrpc.json` line 1614 at r3](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-N9RKCsk7JIuD2eQTSRE:-N9S05fS7Z2pcFODd3T7:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4fdf0c7993593afc666290b740471421a72cdfb1/api/starknet_api_openrpc.json#L1614)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

the object properties should be under `properties`.
so it should be:
```
EVENT_ABI_ENTRY : {
  "type" : "object",
  "properties" : {
    "type" : { ... },
   "name" : {...}
   ...
  }
}
```


</blockquote></details>

Done.

**Review by lior-stark — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArielElp)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43#-:-N9jkD-L0ycFqdEH5pwC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArielElp)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
