### PR TITLE
adding block number to emitted event

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/1)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
the addition of the field looks ok, but we need to bump the schema version (`info/version` attribute) as well.
this is a non-breaking change, so it should bump the minor version, i.e. to 0.5.3.

**Review by ArielElp — COMMENTED** [review]
bumped

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/1#-:-MyBCiWR-Zx-iXQNPvBZ:b-sik5eu)* status: 0 of 1 files reviewed, all discussions resolved

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/1#-:-MyBOtBo5LJMLO85VVS7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
