### PR TITLE
fix(RPC-SPEC): fix block transaction structure

### PR DESCRIPTION
**Pull request by nagmo-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/121)

### CODE REVIEW

**Comment by nagmo-starkware** [comment]
Current dependencies on/for this PR:
* master
  * **PR #121** <a href="https://app.graphite.dev/github/pr/starkware-libs/starknet-specs/121" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/starknet-specs/121?utm_source=stack-comment).

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/121)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EvyatarO and @nagmo-starkware)

___
*[`api/starknet_api_openrpc.json` line 1317 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/121#-NaooFxxBQDpdeUt1IWS:-NaooFxxBQDpdeUt1IWT:bb7avzj) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/471ccca8227f148865b86efbc730180e9635d1e7/api/starknet_api_openrpc.json#L1317)):*
> ```JSON
>                                 },
>                                 {
>                                     "transaction_hash": {
> ```

Shouldn't this be type: object with one required property, "transaction_hash"?

**Review by nagmo-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/121)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @EvyatarO)

___
*[`api/starknet_api_openrpc.json` line 1317 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/121#-NaooFxxBQDpdeUt1IWS:-Nap7MbSA-jhojcgQcL0:blpckfc) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/471ccca8227f148865b86efbc730180e9635d1e7/api/starknet_api_openrpc.json#L1317)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Shouldn't this be type: object with one required property, "transaction_hash"?
</blockquote></details>

yes I think that will accomplish the same thing

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/121#-:-NaqBDP24LTEogdAh9Li:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvyatarO)

**Pull request merged**
