### PR TITLE
Add block_id to starknet_getNonce

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anatgstarkware, @ArielElp, @bbrandtom, and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 643 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/35#-N7p4gzHB4Wbq5OtcM_B:-N7p4gzHB4Wbq5OtcM_C:b-napcj0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/fac93f194d7e2bddfe3f96ec54c175484afd79aa/api/starknet_api_openrpc.json#L643)):*
> ```JSON
>                     "name": "block_id",
>                     "description": "The hash of the requested block, or number (height) of the requested block, or a block tag",
>                     "required": true,
> ```

why not make it optional and default to latest tag?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 643 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/35#-N7p4gzHB4Wbq5OtcM_B:-N7p5DjWBk3h3Ve0qdIB:b-qhahnh) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/fac93f194d7e2bddfe3f96ec54c175484afd79aa/api/starknet_api_openrpc.json#L643)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

why not make it optional and default to latest tag?
</blockquote></details>

we didn't do that in any other function that gets block _id as a parameter

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 643 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/35#-N7p4gzHB4Wbq5OtcM_B:-N7p5j0UCve5hgUyju8N:bqjffat) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/fac93f194d7e2bddfe3f96ec54c175484afd79aa/api/starknet_api_openrpc.json#L643)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

we didn't do that in any other function that gets block _id as a parameter
</blockquote></details>

but i think the common case would be to simply ask for the latest nonce of an account.
which simply defaults to the latest block.

maybe we need to consider other methods as well.

**Review by lior-stark — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ArielElp, @bbrandtom, and @dan-starkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @dan-starkware)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/35#-:-N8HyRg-DRFTzP1qM-uy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom and @dan-starkware)

**Pull request merged**
