### PR TITLE
add broadcasted_txn type and unify write/estimateFee schemas

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)

### CODE REVIEW

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1144 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jmhTK76KG2sf8oLgN:-N9jmhTK76KG2sf8oLgO:bupp1o4) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1144)):*
> ```JSON
>                 ]
>             },
>             "BROADCASTED_TXN": {
> ```

where is this used in the read API?
in estimating the fee?
___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9jm6GY9vn1pnx_6pxT:b-nhix5h) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
> ```JSON
>                         "$ref": "#/components/schemas/TXN_TYPE"
>                     },
>                     "contract_address": {
> ```

isn't this derived from the contract class, salt and c'tor params?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1144 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jmhTK76KG2sf8oLgN:-N9kLl_a6_WHtbwqJ_BW:b2nign6) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1144)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

where is this used in the read API?
in estimating the fee?
</blockquote></details>

yes
___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9kLt5fAn0HL-l-Ht30:b-pb0ka8) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

isn't this derived from the contract class, salt and c'tor params?
</blockquote></details>

yes, I extracted those to lie in DEPLOY_TXN but not in BROADCASTED_DEPLOY_TXN

**Review by lior-stark — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9p21pMCcZlD8cGDBBJ:b9dhgl1) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

yes, I extracted those to lie in DEPLOY_TXN but not in BROADCASTED_DEPLOY_TXN
</blockquote></details>

so i'm not entirely clear on this.
i see the `contract_address` appearing under DEPLOY_TXN.
but all the properties needed to compute it are also there. So why does the user need to provide the address as well as the properties to compute it?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9yzth89GTzkTzyfhT5:blcox) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so i'm not entirely clear on this.
i see the `contract_address` appearing under DEPLOY_TXN.
but all the properties needed to compute it are also there. So why does the user need to provide the address as well as the properties to compute it?

</blockquote></details>

DEPLOY_TXN is the representation inside a block (when you call some variant of starknet_getBlock, deploy transactions contain the deployed contract address). The address is not part of BROADCASTED_DEPLOY_TXN.

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9zIARB0NGEvkmvab8L:bz5qrg6) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

DEPLOY_TXN is the representation inside a block (when you call some variant of starknet_getBlock, deploy transactions contain the deployed contract address). The address is not part of BROADCASTED_DEPLOY_TXN.
</blockquote></details>

but the address is still computable from the other details, no?
it's not part of the original transaction that was sent by the user, and it can be computed from the other details.
is it there just for convenience?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9zTQW133WNGNv8xOlt:b2vxh2q) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

but the address is still computable from the other details, no?
it's not part of the original transaction that was sent by the user, and it can be computed from the other details.
is it there just for convenience?
</blockquote></details>

yes, do you think it should move to the receipt?

**Review by lior-stark — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @anatgstarkware and @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-N9zk6mz5GScz0NPehga:b-8om1s1) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

yes, do you think it should move to the receipt?
</blockquote></details>

that's what I was thinking.
what's the purpose of this in the transaction?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anatgstarkware and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 1301 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-N9jm6GY9vn1pnx_6pxS:-NA9Mv_x3qTclrN6njLC:b-toyne2) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/68305c0d0b8cffa6e187c72a1808d0c30ee7f848/api/starknet_api_openrpc.json#L1301)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

that's what I was thinking.
what's the purpose of this in the transaction?
</blockquote></details>

Moved to the receipt

**Review by lior-stark — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anatgstarkware and @lior-stark)

**Review by lior-stark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46#-:-NA9bMjHE70h9ujsPNHh:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @anatgstarkware and @lior-stark)

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
