### PR TITLE
v0.6.0: introduce v3 transactions

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)

### CODE REVIEW

**Review by ShahakShama — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @yair-starkware)

___
*[`api/starknet_api_openrpc.json` line 2078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sC-E2B25fjhOjLa7:-Nh0sC-E2B25fjhOjLa8:bfk121f) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2078)):*
> ```JSON
>                                 "title": "Version",
>                                 "description": "Version of the transaction scheme",
>                                 "$ref": "#/components/schemas/NUM_AS_HEX"
> ```

Change into enum with single option (to avoid cases where more than one schema is valid)
___
*[`api/starknet_api_openrpc.json` line 2200 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sLGSCtkvz6sFvzKC:-Nh0sLGSCtkvz6sFvzKD:b-ya81ng) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2200)):*
> ```JSON
>                         "title": "Version",
>                         "description": "Version of the transaction scheme",
>                         "$ref": "#/components/schemas/NUM_AS_HEX"
> ```

Same as above
___
*[`api/starknet_api_openrpc.json` line 2436 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sO2X3Jy_vqCFHTD-:-Nh0sO2X3Jy_vqCFHTD0:b-ya81ng) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2436)):*
> ```JSON
>                                 "title": "Version",
>                                 "description": "Version of the transaction scheme",
>                                 "$ref": "#/components/schemas/NUM_AS_HEX"
> ```

Same as above

**Review by yair-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)* status: all files reviewed, 5 unresolved discussions (waiting on @ArielElp)

*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0cDE06DuJqxOfRsJQ:-Nh0cDE06DuJqxOfRsJR:bfy78gz) (no related file):*
In some cases you use allOf and in some cases you don't

___
___
*[`api/starknet_api_openrpc.json` line 2410 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh10j939IqO4HJ3oDnt:-Nh10j939IqO4HJ3oDnu:bnms79f) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2410)):*
> ```JSON
>                 "title": "Invoke transaction V3",
>                 "description": "initiates a transaction from a given account",
>                 "allOf": [
> ```

Add `"additionalProperties": false`
Preferably to all of the objects

**Review by ArielElp — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`api/starknet_api_openrpc.json` line 2078 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sC-E2B25fjhOjLa7:-Ni8Hp-LBQNJzGr2gTLm:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2078)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Change into enum with single option (to avoid cases where more than one schema is valid)
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 2200 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sLGSCtkvz6sFvzKC:-Ni8HpgRBpZMp4ISZBbt:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2200)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`api/starknet_api_openrpc.json` line 2410 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh10j939IqO4HJ3oDnt:-Ni8Hw78BUgsNZJol9yV:bhfhgg4) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2410)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Add `"additionalProperties": false`
Preferably to all of the objects
</blockquote></details>

are potential collisions solved by explicit requirements in version?
___
*[`api/starknet_api_openrpc.json` line 2436 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh0sO2X3Jy_vqCFHTD-:-Ni8HqT883XKpopgdEFt:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2436)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

**Review by yair-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149)* status: all files reviewed, 3 unresolved discussions (waiting on @ShahakShama)

___
*[`api/starknet_api_openrpc.json` line 2410 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-Nh10j939IqO4HJ3oDnt:-Ni8txOa7DQ5bf1wrlEo:b-4f1mhq) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/4f71f7d2bb9d5aef4e36c4ba68412ea4a3470a06/api/starknet_api_openrpc.json#L2410)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

are potential collisions solved by explicit requirements in version?
</blockquote></details>

That works too

**Review by ShahakShama — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/149#-:-NiA086A5j8zmce1MYVn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
