### PR TITLE
add abi specs

### PR DESCRIPTION
**Pull request by ArielElp**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117)

### CODE REVIEW

**Review by EvyatarO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`api/starknet_api_openrpc.json` line 1274 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/117#-Na5dMT291ZlZWYGawYl:-Na5dMT291ZlZWYGawYm:bb76mu4) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/38b6835bc224240d86a14732cd24b77f8cc888f3/api/starknet_api_openrpc.json#L1274)):*
> ```JSON
>                             },
>                             "required": [
>                                 "trnasaction",
> ```

Why?

**Review by EvyatarO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117#-:-Na5vzQg8JDJ679PLg5g:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117)* status: all files reviewed, 1 unresolved discussion (waiting on @EvyatarO)

___
*[`api/starknet_api_openrpc.json` line 1274 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/117#-Na5dMT291ZlZWYGawYl:-Na5v-Vy1xHNQBKDAZGh:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/38b6835bc224240d86a14732cd24b77f8cc888f3/api/starknet_api_openrpc.json#L1274)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Done.

**Review by EvyatarO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117#-:-Na6m5bY27EB1ztuxBI8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

**Review by EvyatarO — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp)

**Pull request merged**
