### PR TITLE
add SKIP_FEE_CHARGE flag to simulate

### PR DESCRIPTION
**Pull request by EvyatarO**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/109)

### CODE REVIEW

**Review by ArielElp — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/109)* status: all files reviewed, 1 unresolved discussion (waiting on @EvyatarO)

___
*[`api/starknet_trace_api_openrpc.json` line 234 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/109#-NZfSazPB7-4BXDGr_k5:-NZfSazPB7-4BXDGr_k6:b-pi9d9n) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/8c8434a3962fed72f6975dcb014b2cc6a9f382eb/api/starknet_trace_api_openrpc.json#L234)):*
> ```JSON
>                     "SKIP_VALIDATE",
>                     "SKIP_FEE_CHARGE",
>                     "SKIP_EXECUTE"
> ```

remove this
___
*[`api/starknet_trace_api_openrpc.json` line 237 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/109#-NZfSG_eEixqiEkRdnuj:-NZfSG_eEixqiEkRdnuk:b-jf8zkp) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/8c8434a3962fed72f6975dcb014b2cc6a9f382eb/api/starknet_trace_api_openrpc.json#L237)):*
> ```JSON
>                 ],
>                 "description": "Flags that indicate how to simulate a given transaction. The SKIP_FEE_CHARGE, false by default, will simulate also the fee charging phase"
>             },
> ```

By default, the sequencer behavior is replicated locally (enough funds are expected to be in the account, and fee will be deducted from the balance before the simulation of the next transaction). To skip the fee charge, use the SKIP_FEE_CHARGE flag.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/109#-:-NZfYaWhEMdjDIvzGbBR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @EvyatarO)

**Review by EvyatarO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/109)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`api/starknet_trace_api_openrpc.json` line 234 at r1](https://reviewable.io/reviews/starkware-libs/starknet-specs/109#-NZfSazPB7-4BXDGr_k5:-NZfWVaE0C-PKQOYGqs0:b-896fix) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/8c8434a3962fed72f6975dcb014b2cc6a9f382eb/api/starknet_trace_api_openrpc.json#L234)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/109#-:-NZflqyK7rdCxdBV08ZG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvyatarO)

**Pull request merged**
