### PR TITLE
Anatg/api/invalid storage key

### PR DESCRIPTION
**Pull request by anatgstarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)

### CODE REVIEW

**Comment by dan-starkware** [comment]
*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N64dwkh4kfxO_jLipBr:-N64dwkh4kfxO_jLipBs:bq1ks1m) (no related file):*
Did you discuss this with @lior-stark / @arielelp

**Comment by lior-stark** [comment]
*[a discussion](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N64dwkh4kfxO_jLipBr:-N66lpgqCq3znimhwPqW:blcqejq) (no related file):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Did you discuss this with @lior-stark / @arielelp 
</blockquote></details>

yes, we discussed it.

**Review by lior-stark — COMMENTED** [review]
and how is the felt type defined?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-:-N66m3NRAWTF7NOxntre:bq10pm2)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dan-starkware and @lior-stark)

**Review by dan-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-:-N66yPR918ikbvlKSs0b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 964 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tEKB-RvWHrNS1xOE:-N67tEKB-RvWHrNS1xOF:bnlzyfy) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L964)):*
> ```JSON
>                 "$ref": "#/components/schemas/FELT"
>             },
>             "STORAGE_KEY": {
> ```

how is it different from a felt?
___
*[`api/starknet_api_openrpc.json` line 969 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tOIOE8ewtPnt1vWK:-N67tOIOE8ewtPnt1vWL:b76iuc4) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L969)):*
> ```JSON
>                 "$comment": "A storage key, represented as a string of hex digits",
>                 "description": "A storage key. Represented as up to 63 hex digits with leading 4 bits zeroed and msb zeroed.",
>                 "pattern": "^0x0[a-fA-F0-9]{0,62}[0,2,4,6,8,A,a,C,c,E,e]{1}$"
> ```

this means that, for example, `0x01` is invalid.
is that intentional?

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 969 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tOIOE8ewtPnt1vWK:-N67vig79_mEXgoUUOp5:bwlfk6u) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L969)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

this means that, for example, `0x01` is invalid.
is that intentional?
</blockquote></details>

My bad

**Review by anatgstarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 964 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tEKB-RvWHrNS1xOE:-N67vsW-7eI0o-7RhdT_:b5ga34m) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L964)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

how is it different from a felt?
</blockquote></details>

It's  at most 2**251, IIUC 
@arielelp

**Comment by lior-stark** [comment]
*[`api/starknet_api_openrpc.json` line 969 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tOIOE8ewtPnt1vWK:-N67w5zF7AWYHtcg0l32:bddxtxv) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L969)):*
<details><summary><i>Previously, anatgstarkware (anatg) wrote…</i></summary><blockquote>

My bad
</blockquote></details>

so you're setting it to exactly 251 bits?
shouldn't it be the same for FELT?

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ArielElp, @dan-starkware, and @lior-stark)

___
*[`api/starknet_api_openrpc.json` line 969 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tOIOE8ewtPnt1vWK:-N68-hbE5ED_HAX8Rgqb:b-9en6l0) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L969)):*
<details><summary><i>Previously, lior-stark wrote…</i></summary><blockquote>

so you're setting it to exactly 251 bits?
shouldn't it be the same for FELT?
</blockquote></details>

I think that the address space is 0 to 2**251-1 (to be consistent with the commitment being a height 251 MPT with the data placed in the leaves)

**Review by lior-stark — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @ArielElp, and @dan-starkware)

___
*[`api/starknet_api_openrpc.json` line 969 at r2](https://reviewable.io/reviews/starkware-libs/starknet-specs/14#-N67tOIOE8ewtPnt1vWK:-N6C9nB1942jyDZVrMP9:bc0yjuo) ([raw file](https://github.com/starkware-libs/starknet-specs/blob/1c0c230f08b156f363adf6b41beefae3e12de4b1/api/starknet_api_openrpc.json#L969)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that the address space is 0 to 2**251-1 (to be consistent with the commitment being a height 251 MPT with the data placed in the leaves)
</blockquote></details>

and it's a different address space than, for example, contract addresses?

**Review by lior-stark — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dan-starkware)

**Review by anatgstarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-specs/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anatgstarkware)

**Pull request merged**
